apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-chrome-scaledobject
  namespace: keda
  labels: 
    deploymentName: selenium-node-chrome
spec:
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 5
  scaleTargetRef: 
    name: selenium-node-chrome
  triggers:
    - type: selenium-grid
      metadata: 
        url: 'https://10.96.88.7:4444/graphql'
        browserName: 'chrome'